# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Salário')),
                ('cargo', models.CharField(max_length=250, unique=True, verbose_name='Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='EtapaProducao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250, unique=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaEtapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_materia_etapa', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Quantidade Etapa')),
                ('etapa_producao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appprod.EtapaProducao', verbose_name='Etapa Produção')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250, unique=True, verbose_name='Descrição')),
                ('quantidade_estoque', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Quantidade em estoque')),
            ],
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, verbose_name='Data de Nascimento')),
                ('email', models.EmailField(max_length=200, verbose_name='E-Mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appprod.Cargo', verbose_name='Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessoProducao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_termino', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('descricao', models.CharField(max_length=250, unique=True, verbose_name='Descrição')),
                ('prestador', models.ManyToManyField(to='appprod.Prestador')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('sigla', models.CharField(max_length=5, verbose_name='Sigla')),
            ],
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='unidade_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appprod.UnidadeMedida', verbose_name='Unidade de Medida'),
        ),
        migrations.AddField(
            model_name='materiaetapa',
            name='materia_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appprod.MateriaPrima', verbose_name='Matéria Prima'),
        ),
        migrations.AddField(
            model_name='etapaproducao',
            name='materia_etapa',
            field=models.ManyToManyField(through='appprod.MateriaEtapa', to='appprod.MateriaPrima'),
        ),
        migrations.AddField(
            model_name='etapaproducao',
            name='processo_producao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appprod.ProcessoProducao', verbose_name='Processo de Produção'),
        ),
    ]
